### PR TITLE
use the same defaults for session pool config as in the sdk

### LINKED ISSUE #92: use the same default values for session pool as in ydb sdk
[sdk defaults](https://github.com/ydb-platform/ydb-java-sdk/blob/fe3af557f2deb8cde8887b40030abf67d3b78d12/table/src/main/java/tech/ydb/table/impl/pool/SessionPoolOptions.java#L11-L15) vs [yoj defaults](https://github.com/ydb-platform/yoj-project/blob/50a81f595f14ecca8c6cfe2df1b9cbfbce51917a/repository-ydb-v2/src/main/java/tech/ydb/yoj/repository/ydb/YdbConfig.java#L15-L20)

min pool size == 100 and max idle time == 5 minutes  - these values do not look like a reasonable default, I suggest having the same default values as in sdk

### PR DESCRIPTION
**Pull request by cardamo**
fixes #92

### CODE REVIEW

**Comment by nvamelichev** [comment]
@lavrukov **Are you OK with the changes?** Making an explicit default for session pool min size, instead of having min size=max size; and lowering idle time and default min/max pool size seem quite reasonable to me, and also align YOJ with the YDB Java SDK behavior.

I believe that anybody on the Right has either configured YDB session pool explicitly (if they care) or won't notice and/or care if the defaults change slightly.

**Comment by nvamelichev** [comment]
@cardamo Artem, let's take the pool defaults from SessionPoolOptions.DEFAULT constant in the SDK (it's public). Otherwise LGTM

**Comment by cardamo** [comment]
nope, getters in tech.ydb.table.impl.pool.SessionPoolOptions are package-private :man_shrugging:

**Review by nvamelichev — CHANGES_REQUESTED** [review]
:-1: After discussions with @lavrukov, I'm declining this PR as too risky for Right's Cloud Java (sorry).

- Short-term: We probably should change/enforce defaults in our libraries, instead.
- Also of note: Why the hell does YDB Java SDK not check that sessions are alive? Do we maybe need to make improvements there, or do we maybe need to enable some YDB Java SDK feature that will check sessions for liveness?

**Pull request closed without merging**
