### PR TITLE
enum DbType

### PR DESCRIPTION
**Pull request by lavrukov**

### CODE REVIEW

**Comment by nvamelichev** [comment]
Let's bump version in `pom.xml` to `2.0.0-SNAPSHOT` because we've changed the API incompatibly... and also change `JavaField.getDbType()` to return `DbType` enum because we've changed the API :-)

**Comment by nvamelichev** [comment]
The tests fail:

**Comment by lavrukov** [comment]
> The tests fail:
> 
> ```
> [ERROR] Failures: 
> [ERROR]   ColumnTest.annotatedFieldDbTypeTest:60 
> Expecting ArrayList:
>   ["UINT32"]
> to contain only:
>   ["UInt32"]
> element(s) not found:
>   ["UInt32"]
> and element(s) not expected:
>   ["UINT32"]
> ```

done

**Comment by nvamelichev** [comment]
Now that we return `DbType.DEFAULT` instead of `""`, one fragile test has failed:
```
[ERROR] tech.ydb.yoj.databind.schema.naming.ColumnTest.plainFieldTypeTest -- Time elapsed: 0.015 s <<< FAILURE!
java.lang.AssertionError: 

Expecting empty but was: [DEFAULT, DEFAULT, DEFAULT]
	at tech.ydb.yoj.databind.schema.naming.ColumnTest.plainFieldTypeTest(ColumnTest.java:52)
```

**Review by nvamelichev — APPROVED** [review]
LGTM :+1:

**Pull request merged**
